apiVersion : apps/v1
kind : Deployment
metadata : 
  name : parichay-be-restapp-deployment
  labels :
    app : parichay-be-restapp
    tier : backend
spec : 
  replicas : 3
  selector : 
    matchLabels : 
      app : parichay-be-restapp
  template : 
    metadata : 
      labels : 
        app : parichay-be-restapp
        tier : backend
    spec : 
      containers :
        - name : parichay-be-restapp-container
          image : stacksimplify/kube-helloworld:1.0.0
          ports : 
            - containerPort : 8080
